// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taratra.Models;

#nullable disable

namespace Taratra.Migrations
{
    [DbContext(typeof(TaratraDbContext))]
    partial class TaratraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Taratra.Models.AnneeScolaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnneeScolaires");
                });

            modelBuilder.Entity("Taratra.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EcoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Taratra.Models.Ecole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ecoles");
                });

            modelBuilder.Entity("Taratra.Models.Eleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("Taratra.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeScolaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Option")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("EleveId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("Taratra.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeMatiere")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("Taratra.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeScolaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleveId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NoteObtenue")
                        .HasColumnType("REAL");

                    b.Property<int>("PeriodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemeEvaluationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("EleveId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("SystemeEvaluationId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Taratra.Models.Periode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ordre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Periodes");
                });

            modelBuilder.Entity("Taratra.Models.SystemeEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<int>("MatiereId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeEvaluationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("TypeEvaluationId");

                    b.ToTable("SystemeEvaluations");
                });

            modelBuilder.Entity("Taratra.Models.TypeEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ordre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TypeEvaluations");
                });

            modelBuilder.Entity("Taratra.Models.Classe", b =>
                {
                    b.HasOne("Taratra.Models.Ecole", null)
                        .WithMany("Classes")
                        .HasForeignKey("EcoleId");
                });

            modelBuilder.Entity("Taratra.Models.Inscription", b =>
                {
                    b.HasOne("Taratra.Models.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Inscriptions")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.Classe", "Classe")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.Eleve", "Eleve")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("Taratra.Models.Note", b =>
                {
                    b.HasOne("Taratra.Models.AnneeScolaire", "AnneeScolaire")
                        .WithMany()
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.Periode", "Periode")
                        .WithMany("Notes")
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.SystemeEvaluation", "SystemeEvaluation")
                        .WithMany("Notes")
                        .HasForeignKey("SystemeEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Eleve");

                    b.Navigation("Periode");

                    b.Navigation("SystemeEvaluation");
                });

            modelBuilder.Entity("Taratra.Models.SystemeEvaluation", b =>
                {
                    b.HasOne("Taratra.Models.Classe", "Classe")
                        .WithMany("SystemesEvaluations")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.Matiere", "Matiere")
                        .WithMany("SystemesEvaluations")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taratra.Models.TypeEvaluation", "TypeEvaluation")
                        .WithMany("SystemesEvaluations")
                        .HasForeignKey("TypeEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Matiere");

                    b.Navigation("TypeEvaluation");
                });

            modelBuilder.Entity("Taratra.Models.AnneeScolaire", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("Taratra.Models.Classe", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("SystemesEvaluations");
                });

            modelBuilder.Entity("Taratra.Models.Ecole", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Taratra.Models.Eleve", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Taratra.Models.Matiere", b =>
                {
                    b.Navigation("SystemesEvaluations");
                });

            modelBuilder.Entity("Taratra.Models.Periode", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Taratra.Models.SystemeEvaluation", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Taratra.Models.TypeEvaluation", b =>
                {
                    b.Navigation("SystemesEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
